[server]
headless = true
fileWatcherType = "poll"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0a0a0a"
backgroundColor = "#f5f5f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#0a0a0a"
font = "sans serif"
